#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=./stack-env.sh
source "$ROOT_DIR/scripts/stack-env.sh"

if [[ "$#" -lt 2 ]]; then
  echo "usage: $0 <stack-slot> <make-target> [extra make args...]" >&2
  exit 2
fi

STACK_SLOT="$1"
target="$2"
shift 2
STACK_SLOT_WIDTH="${STACK_SLOT_WIDTH:-100}"

unset \
  PORT_OFFSET STACK_INSTANCE_SUFFIX \
  APIM_GATEWAY_PORT GRAFANA_PORT OTEL_GRPC_PORT OTEL_HTTP_PORT KEYCLOAK_PORT OPERATOR_CONSOLE_PORT EDGE_HTTP_PORT EDGE_TLS_HTTP_PORT EDGE_TLS_PORT TODO_FRONTEND_PORT VITE_DEV_PORT \
  APIM_BASE_URL APIM_LOOPBACK_BASE_URL GRAFANA_BASE_URL KEYCLOAK_BASE_URL OIDC_ISSUER_EXTERNAL OPERATOR_CONSOLE_URL \
  TODO_FRONTEND_BASE_URL TODO_FRONTEND_BROWSER_URL TODO_FRONTEND_ORIGIN_LOCALHOST TODO_FRONTEND_ORIGIN_LOOPBACK TODO_APIM_BASE_URL TODO_APIM_PUBLIC_BASE_URL TODO_GRAFANA_BASE_URL TODO_OBSERVABILITY_DASHBOARD_URL \
  APIM_ALLOWED_ORIGIN_BROWSER_LOCALHOST APIM_ALLOWED_ORIGIN_OPERATOR_CONSOLE APIM_ALLOWED_ORIGIN_VITE APIM_ALLOWED_ORIGIN_GATEWAY \
  EDGE_HTTP_BASE_URL EDGE_TLS_BASE_URL \
  SMOKE_HELLO_BASE_URL SMOKE_HELLO_KEYCLOAK_BASE_URL SMOKE_OIDC_BASE_URL SMOKE_OIDC_KEYCLOAK_BASE_URL SMOKE_MCP_URL SMOKE_EDGE_BASE_URL

export STACK_SLOT STACK_SLOT_WIDTH
stack_env_init

cd "$ROOT_DIR"
exec make "$target" STACK_SLOT="$STACK_SLOT" STACK_SLOT_WIDTH="$STACK_SLOT_WIDTH" "$@"
